services:
  neolink-ui:
    image: ll0rd/neolink-ui:latest
    container_name: neolink-ui
    network_mode: host
    environment:
      - NEOLINK_UI_PASSWORD=${NEOLINK_UI_PASSWORD:-}
      - NEOLINK_MODE=${NEOLINK_MODE:-rtsp}
    volumes:
      - ./config:/config
    restart: unless-stopped
